# @format

trailingComma: "es5"
tabWidth: 2
semi: true
singleQuote: false
bracketSpacing: true
arrowParens: avoid
insertPragma: true
printWidth: 80
useTabs: false
quoteProps: as-needed
bracketSameLine: true
jsxSingleQuote: false
proseWrap: always
htmlWhitespaceSensitivity: strict
vueIndentScriptAndStyle: true
endOfLine: lf
embeddedLanguageFormatting: auto
singleAttributePerLine: false
